name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-python@v2
      uses: pre-commit/action@v2.0.3
    
    - name: Git add
      run: |
          git add _data
          git add data
